//
function stage_param(){

global.ds_stage_param = ds_grid_create(30, 10);

var _ds = global.ds_stage_param;

_ds[# STAGENAME.TEST, STAGEPARAM.STAGEID] = r_test;
_ds[# STAGENAME.TEST, STAGEPARAM.NAMEEN] = "TEST@ROOM";
_ds[# STAGENAME.TEST, STAGEPARAM.NAMEJP] = "テスト@ルーム";
_ds[# STAGENAME.TEST, STAGEPARAM.BGM] = "";
_ds[# STAGENAME.TEST, STAGEPARAM.NEXTSTAGE] = r_stage1;
_ds[# STAGENAME.HELLCAVE1, STAGEPARAM.STAGENUM] = 0;

#region hellcave
_ds[# STAGENAME.HELLCAVE1, STAGEPARAM.STAGEID] = r_stage1;
_ds[# STAGENAME.HELLCAVE1, STAGEPARAM.NAMEEN] = "HELL@CAVE";
_ds[# STAGENAME.HELLCAVE1, STAGEPARAM.NAMEJP] = "ヘルケイヴ";
_ds[# STAGENAME.HELLCAVE1, STAGEPARAM.BGM] = "";
_ds[# STAGENAME.HELLCAVE1, STAGEPARAM.NEXTSTAGE] = r_stage2;
_ds[# STAGENAME.HELLCAVE1, STAGEPARAM.STAGENUM] = 1;

_ds[# STAGENAME.HELLCAVE2, STAGEPARAM.STAGEID] = r_stage2;
_ds[# STAGENAME.HELLCAVE2, STAGEPARAM.NAMEEN] = "HELL@CAVE";
_ds[# STAGENAME.HELLCAVE2, STAGEPARAM.NAMEJP] = "ヘルケイヴ";
_ds[# STAGENAME.HELLCAVE2, STAGEPARAM.BGM] = "";
_ds[# STAGENAME.HELLCAVE2, STAGEPARAM.NEXTSTAGE] = r_stage3;
_ds[# STAGENAME.HELLCAVE2, STAGEPARAM.STAGENUM] = 2;

_ds[# STAGENAME.HELLCAVE3, STAGEPARAM.STAGEID] = r_stage3;
_ds[# STAGENAME.HELLCAVE3, STAGEPARAM.NAMEEN] = "HELL@CAVE";
_ds[# STAGENAME.HELLCAVE3, STAGEPARAM.NAMEJP] = "ヘルケイヴ";
_ds[# STAGENAME.HELLCAVE3, STAGEPARAM.BGM] = "";
_ds[# STAGENAME.HELLCAVE3, STAGEPARAM.NEXTSTAGE] = r_stage4;
_ds[# STAGENAME.HELLCAVE3, STAGEPARAM.STAGENUM] = 3;

_ds[# STAGENAME.HELLCAVE4, STAGEPARAM.STAGEID] = r_stage4;
_ds[# STAGENAME.HELLCAVE4, STAGEPARAM.NAMEEN] = "HELL@CAVE";
_ds[# STAGENAME.HELLCAVE4, STAGEPARAM.NAMEJP] = "ヘルケイヴ";
_ds[# STAGENAME.HELLCAVE4, STAGEPARAM.BGM] = "";
_ds[# STAGENAME.HELLCAVE4, STAGEPARAM.NEXTSTAGE] = r_stage5;
_ds[# STAGENAME.HELLCAVE4, STAGEPARAM.STAGENUM] = 4;

_ds[# STAGENAME.HELLCAVE5, STAGEPARAM.STAGEID] = r_stage5;
_ds[# STAGENAME.HELLCAVE5, STAGEPARAM.NAMEEN] = "HELL@CAVE";
_ds[# STAGENAME.HELLCAVE5, STAGEPARAM.NAMEJP] = "ヘルケイヴ";
_ds[# STAGENAME.HELLCAVE5, STAGEPARAM.BGM] = "";
_ds[# STAGENAME.HELLCAVE5, STAGEPARAM.NEXTSTAGE] = r_stage1;
_ds[# STAGENAME.HELLCAVE5, STAGEPARAM.STAGENUM] = 5;

#endregion


enum STAGENAME{
	HELLCAVE1,
	HELLCAVE2,
	HELLCAVE3,
	HELLCAVE4,
	HELLCAVE5,
	
	HELLLAKE1,
	HELLLAKE2,
	HELLLAKE3,
	HELLFOREST1,
	HELLFOREST2,
	HELLFOREST3,
	ABYSS1,
	ABYSS2,
	ABYSS3,
	CORE,
	TEST,
}
enum STAGEPARAM{
	STAGEID,
	NAMEEN,
	NAMEJP,
	BGM,
	NEXTSTAGE,
	STAGENUM,
}
}