//
function stage_param(){

global.ds_stage_param = ds_grid_create(30, 10);

var _ds = global.ds_stage_param;

_ds[# STAGENAME.TEST, STAGEPARAM.STAGEID] = r_test;
_ds[# STAGENAME.TEST, STAGEPARAM.NAMEEN] = "TEST"+chr(13)+"ROOM";
_ds[# STAGENAME.TEST, STAGEPARAM.NAMEJP] = "テスト"+chr(13)+"ルーム";
_ds[# STAGENAME.TEST, STAGEPARAM.BGM] = "";
_ds[# STAGENAME.TEST, STAGEPARAM.NEXTSTAGE] = r_stage1;


_ds[# STAGENAME.HELLCAVE1, STAGEPARAM.STAGEID] = r_stage1;
_ds[# STAGENAME.HELLCAVE1, STAGEPARAM.NAMEEN] = "HELL"+chr(13)+"CAVE";
_ds[# STAGENAME.HELLCAVE1, STAGEPARAM.NAMEJP] = "ヘルケイヴ";
_ds[# STAGENAME.HELLCAVE1, STAGEPARAM.BGM] = "";
_ds[# STAGENAME.HELLCAVE1, STAGEPARAM.NEXTSTAGE] = r_test;


enum STAGENAME{
	HELLCAVE1,
	HELLCAVE2,
	HELLCAVE3,
	HELLLAKE1,
	HELLLAKE2,
	HELLLAKE3,
	HELLFOREST1,
	HELLFOREST2,
	HELLFOREST3,
	ABYSS1,
	ABYSS2,
	ABYSS3,
	CORE,
	TEST,
}
enum STAGEPARAM{
	STAGEID,
	NAMEEN,
	NAMEJP,
	BGM,
	NEXTSTAGE,
	
}
}