
var _achievement_num = 15;

draw_achievement_window_queue = array_create(12, noone);
now_draw_achievement_window = noone;
achievement_window_time = achievement_window_time_base;
length = 0;

global.achievement_param = ds_grid_create(_achievement_num, 20);

for(var i=0; i<_achievement_num; i++){
	global.achievement_param[# i, ACHIEVEMENT_PARAM.ACQUIRED] = false;
	global.achievement_param[# i, ACHIEVEMENT_PARAM.GETTABLE] = false;
	global.achievement_param[# i, ACHIEVEMENT_PARAM.HIDDEN_DESCRIPTION_EN] = "";
	global.achievement_param[# i, ACHIEVEMENT_PARAM.HIDDEN_DESCRIPTION_JP] = "";
	global.achievement_param[# i, ACHIEVEMENT_PARAM.ENABLE] = false;
	global.achievement_param[# i, ACHIEVEMENT_PARAM.WINDOW_DRAWTIME] = achievement_window_time_base;
}

global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.NAMEEN] = "HELLCAVE";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.NAMEJP] = "ヘルケイヴ";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "REACH HELLCAVE";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ヘルケイヴに辿り着く";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.DRAWDESCRIPTION] = false;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.SUBIMAGE] = 0;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.ENABLE] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.WINDOW_DRAWTIME] = 90;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.NAMEEN] = "HELLFOREST";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.NAMEJP] = "ヘルフォレスト";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "REACH HELLFOREST";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ヘルフォレストに辿り着く";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.DRAWDESCRIPTION] = false;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.SUBIMAGE] = 1;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.ENABLE] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.WINDOW_DRAWTIME] = 90;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.NAMEEN] = "HELLLAKE";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.NAMEJP] = "ヘルレイク";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "REACH HELLLAKE";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ヘルレイクに辿り着く";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.DRAWDESCRIPTION] = false;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.SUBIMAGE] = 2;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.ENABLE] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.WINDOW_DRAWTIME] = 90;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEEN] = "HELLMOUNTAIN";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEJP] = "ヘルマウンテン";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "REACH HELLMOUNTAIN";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ヘルマウンテンに辿り着く";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DRAWDESCRIPTION] = false;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.SUBIMAGE] = 3;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.ENABLE] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.WINDOW_DRAWTIME] = 90;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.NAMEEN] = "ALTAR";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.NAMEJP] = "アルター";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "REACH ALTAR";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "アルターに辿り着く";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.DRAWDESCRIPTION] = false;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.SUBIMAGE] = 4;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.ENABLE] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.WINDOW_DRAWTIME] = 90;


global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.NAMEEN] = "VICTORY";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.NAMEJP] = "勝利";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "BEAT THE GAME";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ゲームをクリアする";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.DRAWDESCRIPTION] = true;
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.SUBIMAGE] = 5;
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.ENABLE] = true;


global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.NAMEEN] = "STRONGEST";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.NAMEJP] = "最強";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "BEAT THE GAME ON VERYHARD";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "難易度VERYHARDで@ゲームをクリアする";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.DRAWDESCRIPTION] = true;
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.SUBIMAGE] = 6;
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.ENABLE] = true;


global.achievement_param[# ACHIEVEMENT_NAME.FIND_HELLMODE, ACHIEVEMENT_PARAM.NAMEEN] = "HIDDEN MODE?";
global.achievement_param[# ACHIEVEMENT_NAME.FIND_HELLMODE, ACHIEVEMENT_PARAM.NAMEJP] = "隠しモード？";
global.achievement_param[# ACHIEVEMENT_NAME.FIND_HELLMODE, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "FIND HELLMODE";
global.achievement_param[# ACHIEVEMENT_NAME.FIND_HELLMODE, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ヘルモードを見つける";
global.achievement_param[# ACHIEVEMENT_NAME.FIND_HELLMODE, ACHIEVEMENT_PARAM.DRAWDESCRIPTION] = true;
global.achievement_param[# ACHIEVEMENT_NAME.FIND_HELLMODE, ACHIEVEMENT_PARAM.SUBIMAGE] = 7;
global.achievement_param[# ACHIEVEMENT_NAME.FIND_HELLMODE, ACHIEVEMENT_PARAM.ENABLE] = true;


global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_HELLMODE, ACHIEVEMENT_PARAM.NAMEEN] = "CHALLENGER";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_HELLMODE, ACHIEVEMENT_PARAM.NAMEJP] = "挑戦者";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_HELLMODE, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "BEAT THE GAME ON HELLMODE";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_HELLMODE, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ヘルモードでゲームを@クリアする";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_HELLMODE, ACHIEVEMENT_PARAM.DRAWDESCRIPTION] = false;
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_HELLMODE, ACHIEVEMENT_PARAM.SUBIMAGE] = 8;
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_HELLMODE, ACHIEVEMENT_PARAM.ENABLE] = true;


global.achievement_param[# ACHIEVEMENT_NAME.ALLCLEAR_TRUEHELLMODE, ACHIEVEMENT_PARAM.NAMEEN] = "TRUE HELL";
global.achievement_param[# ACHIEVEMENT_NAME.ALLCLEAR_TRUEHELLMODE, ACHIEVEMENT_PARAM.NAMEJP] = "真の地獄";
global.achievement_param[# ACHIEVEMENT_NAME.ALLCLEAR_TRUEHELLMODE, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "BEAT THE GAME ON VERYHARD@WITH ALL HELLMODE OPTIONS";
global.achievement_param[# ACHIEVEMENT_NAME.ALLCLEAR_TRUEHELLMODE, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "難易度VERYHARDで@ヘルモードオプションを@すべてONにしてクリアする";
global.achievement_param[# ACHIEVEMENT_NAME.ALLCLEAR_TRUEHELLMODE, ACHIEVEMENT_PARAM.DRAWDESCRIPTION] = false;
global.achievement_param[# ACHIEVEMENT_NAME.ALLCLEAR_TRUEHELLMODE, ACHIEVEMENT_PARAM.SUBIMAGE] = 9;
global.achievement_param[# ACHIEVEMENT_NAME.ALLCLEAR_TRUEHELLMODE, ACHIEVEMENT_PARAM.ENABLE] = true;


global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NO_MOVEKEY, ACHIEVEMENT_PARAM.NAMEEN] = "DON'T NEED WASD";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NO_MOVEKEY, ACHIEVEMENT_PARAM.NAMEJP] = "WASDなんて必要ない";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NO_MOVEKEY, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "REACH HELLMOUTAIN WITHOUT@USING MOVEMENT KEYS";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NO_MOVEKEY, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "移動キーを使わずに@ヘルマウンテンに辿り着く";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NO_MOVEKEY, ACHIEVEMENT_PARAM.DRAWDESCRIPTION] = false;
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NO_MOVEKEY, ACHIEVEMENT_PARAM.SUBIMAGE] = 10;
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NO_MOVEKEY, ACHIEVEMENT_PARAM.ENABLE] = true;


global.achievement_param[# ACHIEVEMENT_NAME.GET_ALL_ACHIEVEMENT, ACHIEVEMENT_PARAM.NAMEEN] = "HELLFROG";
global.achievement_param[# ACHIEVEMENT_NAME.GET_ALL_ACHIEVEMENT, ACHIEVEMENT_PARAM.NAMEJP] = "HELLFROG";
global.achievement_param[# ACHIEVEMENT_NAME.GET_ALL_ACHIEVEMENT, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "GET ALL ACHIEVEMENTS";
global.achievement_param[# ACHIEVEMENT_NAME.GET_ALL_ACHIEVEMENT, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "すべての実績を解除する";
global.achievement_param[# ACHIEVEMENT_NAME.GET_ALL_ACHIEVEMENT, ACHIEVEMENT_PARAM.HIDDEN_DESCRIPTION_EN] = "THANK YOU FOR PLAYING!!";
global.achievement_param[# ACHIEVEMENT_NAME.GET_ALL_ACHIEVEMENT, ACHIEVEMENT_PARAM.HIDDEN_DESCRIPTION_JP] = "たくさん遊んでくれて@ありがとう！";
global.achievement_param[# ACHIEVEMENT_NAME.GET_ALL_ACHIEVEMENT, ACHIEVEMENT_PARAM.DRAWDESCRIPTION] = true;
global.achievement_param[# ACHIEVEMENT_NAME.GET_ALL_ACHIEVEMENT, ACHIEVEMENT_PARAM.SUBIMAGE] = 11;
global.achievement_param[# ACHIEVEMENT_NAME.GET_ALL_ACHIEVEMENT, ACHIEVEMENT_PARAM.ENABLE] = true;



enum ACHIEVEMENT_NAME{
	REACH_HELLCAVE,
	REACH_HELLFOREST,
	REACH_HELLLAKE,
	REACH_HELLMOUNTAIN,
	REACH_ALTAR,
	
	CLEAR_NORMAL,
	CLEAR_VERYHARD,
	
	FIND_HELLMODE,
	CLEAR_HELLMODE,
	ALLCLEAR_TRUEHELLMODE,
	
	CLEAR_NO_MOVEKEY,
	
	GET_ALL_ACHIEVEMENT,
	
}
enum ACHIEVEMENT_PARAM{
	ACQUIRED,
	NAMEEN,
	NAMEJP,
	DESCRIPTION_EN,
	DESCRIPTION_JP,
	DRAWICON,
	DRAWDESCRIPTION,
	SUBIMAGE,
	HIDDEN_DESCRIPTION_EN,
	HIDDEN_DESCRIPTION_JP,
	GETTABLE,
	ENABLE,
	WINDOW_DRAWTIME,
}