
var _achievement_num = 15;

global.achievement_param = ds_grid_create(_achievement_num, 7);

for(var i=0; i<_achievement_num; i++){
	global.achievement_list[# i, ACHIEVEMENT_PARAM.ACQUIRED] = false;
	
	
}

global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.NAMEEN] = "HELLCAVE";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.NAMEJP] = "ヘルケイヴ";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "Reach HELLCAVE";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ヘルケイヴに辿り着く";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.DRAWICON] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLCAVE, ACHIEVEMENT_PARAM.SUBIMAGE] = 0;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.NAMEEN] = "HELLFOREST";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.NAMEJP] = "ヘルフォレスト";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "Reach HELLFOREST";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ヘルフォレストに辿り着く";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.DRAWICON] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLFOREST, ACHIEVEMENT_PARAM.SUBIMAGE] = 1;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.NAMEEN] = "HELLLAKE";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.NAMEJP] = "ヘルレイク";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "Reach HELLLAKE";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ヘルレイクに辿り着く";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.DRAWICON] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLLAKE, ACHIEVEMENT_PARAM.SUBIMAGE] = 2;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEEN] = "HELLMOUNTAIN";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEJP] = "ヘルマウンテン";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "Reach HELLMOUNTAIN";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ヘルマウンテンに辿り着く";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DRAWICON] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.SUBIMAGE] = 3;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.NAMEEN] = "ALTAR";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.NAMEJP] = "アルター";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "Reach ALTAR";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "アルターに辿り着く";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.DRAWICON] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_ALTAR, ACHIEVEMENT_PARAM.SUBIMAGE] = 4;


global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.NAMEEN] = "GAME CLEAR!";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.NAMEJP] = "ゲームクリア!";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "THANKYOU FOR PLAYING!";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "プレイありがとうございました！";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.DRAWICON] = true;
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_NORMAL, ACHIEVEMENT_PARAM.SUBIMAGE] = 5;


global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.NAMEEN] = "VERYHARD CLEAR!";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.NAMEJP] = "ベリーハードクリア!";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "BEAT THE VERYHARD DIFFICULTY";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "難易度ベリーハードでゲームをクリアする";
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.DRAWICON] = true;
global.achievement_param[# ACHIEVEMENT_NAME.CLEAR_VERYHARD, ACHIEVEMENT_PARAM.SUBIMAGE] = 6;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEEN] = "HIDDEN MODE?";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEJP] = "隠しモード？";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "Find HELLMODE";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ヘルモードを見つける";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DRAWICON] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.SUBIMAGE] = 7;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEEN] = "";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEJP] = "";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "BEAT THE GAME ON HELLMODE";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "ヘルモードでゲームをクリアする";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DRAWICON] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.SUBIMAGE] = 8;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEEN] = "TRUE HELL";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEJP] = "真の地獄";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "BEAT THE GAME ON VERYHARD WITH ALL HELLMODE OPTIONS";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "難易度VeryHardでヘルモードオプションをすべてONにしてクリアする";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DRAWICON] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.SUBIMAGE] = 9;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEEN] = "Don't need WASD";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEJP] = "WASDなんて必要ない";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "Beat the game without using the movement keys";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "移動キーを使わずにゲームをクリアする";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DRAWICON] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.SUBIMAGE] = 10;


global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEEN] = "HELLFROG";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.NAMEJP] = "HELLFROG";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_EN] = "THHHHANK YOOOU FORR PLLLAYYYING";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DESCRIPTION_JP] = "こんなに遊んでくれてありがとう……";
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.DRAWICON] = true;
global.achievement_param[# ACHIEVEMENT_NAME.REACH_HELLMOUNTAIN, ACHIEVEMENT_PARAM.SUBIMAGE] = 11;



enum ACHIEVEMENT_NAME{
	REACH_HELLCAVE,
	REACH_HELLFOREST,
	REACH_HELLLAKE,
	REACH_HELLMOUNTAIN,
	REACH_ALTAR,
	
	CLEAR_NORMAL,
	CLEAR_VERYHARD,
	
	FIND_HELLMODE,
	CLEAR_HELLMODE,
	ALLCLEAR_TRUEHELLMODE,
	
	CLEAR_NO_MOVEKEY,
	
	GET_ALL_ACHIEVEMENT,
	
}
enum ACHIEVEMENT_PARAM{
	ACQUIRED,
	NAMEEN,
	NAMEJP,
	DESCRIPTION_EN,
	DESCRIPTION_JP,
	DRAWICON,
	DRAWDESCRIPTION,
	SUBIMAGE,
	
	
	
}